### ISSUE TITLE
번역 분석기 오류

### ISSUE THREAD

**Issue by 94HanA** [csh1668/RimworldExtractor#1]
![image](https://github.com/csh1668/RimworldExtractor/assets/111541485/719a2bb0-e9fa-4351-8b27-92cd13a379ed)

이 상태에서 선택된 파일들 수정 누르면

![image](https://github.com/csh1668/RimworldExtractor/assets/111541485/9029f5bd-db01-4f1f-b1e8-7efc779439f7)

요렇게 뜸

log.txt

경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 vanillaracesexpanded.android인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 VanillaExpanded.VCEF인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 sarg.alphabiomes인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 SirMashedPotato.Ashlands인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 sarg.alphaanimals인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 VanillaExpanded.VFEArchitect인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 VanillaExpanded.VPlantsEMore인 모드를 찾을 수 없었습니다.
경고::Extractor.DoXmlInheritance()::자식 노드=PortableStove의 부모 노드=Campfire를 찾을 수 없었습니다. 
경고::Extractor.DoXmlInheritance()::자식 노드=NCS_TentFloor의 부모 노드=CarpetBase를 찾을 수 없었습니다. 
메시지::CompatManager..cctor()::3개의 compat가 로드됨
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 imranfish.xmlextensions인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 CETeam.CombatExtended인 모드를 찾을 수 없었습니다.
경고::ModLister.TryGetModMetadataByPackageId()::모드 폴더에서 packageId가 VanillaExpanded.VFEArchitect인 모드를 찾을 수 없었습니다.

**Comment by csh1668** [comment]
제보 ㄳㄳ

수정 완료했고 아마 한 5분쯤 뒤에 프로그램 다시 키면
왼쪽에 업데이트 됐으니까 새로 받으라고 링크 뜰꺼임
