### ISSUE TITLE
풀리스트 ->xml 변환시 누락 증상

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#11]
[0.8.2]

<img width="200" alt="화면 캡처 2024-04-29 220326" src="https://github.com/csh1668/RimworldExtractor/assets/150018627/e734787d-f3bb-46ba-83e4-7111b0af9867"><br>

#6 이랑 비슷한데

이번엔 하나의 defType에 속한 풀리스트 노드들 중에서

스프레드 시트상 제일 나중에 위치한 Def 하나에 해당하는 리스트만 변환이 돼요

😭

**Comment by RimWorldKorea** [comment]
아닌가 좀 더 살펴봐야겠어요

**Comment by csh1668** [comment]
증감 연산자를 안썼네요 😨 ㅋㅋㅋㅋ
