### ISSUE TITLE
[★★★] full-list 번역 xml 파일을 xlsx로 변환 시 의도되지 않은 동작

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#13]
예를 들어

    <I_BasicImplants.generalRules.rulesStrings>
      <li>subject-&gt;기초 이식물</li>
      <li>subject_story-&gt;그들은 내부에 이식한 체온 조절기 덕분에 악랄한 핵 겨울을 견뎌냈습니다.</li>
      <li>subject_story-&gt;고대 군인에게 추격당했을 때, 그들이 생각보다 훨씬 빨리 깨어난 이유는 그들의 동면 치료장치 때문이었습니다.</li>
      <li>subject_story-&gt;전투기를 통째로 집어든 반란군 사이보그와 함께 싸웠습니다.</li>
      <li>subject_gerund-&gt;이식물 제작 중</li>
    </I_BasicImplants.generalRules.rulesStrings>

를 변환하면

    ResearchProjectDef+I_BasicImplants.generalRules.rulesStrings | subject->기초 이식물subject_story->그들은 내부에 이식한 체온 조절기 덕분에 악랄한 핵 겨울을 견뎌냈습니다.subject_story->고대 군인에게 추격당했을 때, 그들이 생각보다 훨씬 빨리 깨어난 이유는 그들의 동면 치료장치 때문이었습니다.subject_story->전투기를 통째로 집어든 반란군 사이보그와 함께 싸웠습니다.subject_gerund->이식물 제작 중

처럼 죄다 붙어버려요

**Comment by csh1668** [comment]
추출하는 모드 정보좀 부탁드립니다

**Comment by RimWorldKorea** [comment]
모드는 [Integrated Implants](https://steamcommunity.com/sharedfiles/filedetails/?id=3223443793)인데 특정 모드에서만 그러진 않고 다 그러더라구요
[Integrated Implants - 3223443793.xlsx](https://github.com/csh1668/RimworldExtractor/files/15389641/Integrated.Implants.-.3223443793.xlsx)의 597행 참조
