### ISSUE TITLE
[★] comps 노드의 리스트 번호가 제대로 붙지 않는 현상

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#14]
https://github.com/RimWorldKorea/RMK/issues/832 과정에서 발견

원래라면 6번을 받아야 할 reloadaable comp가 0번이 되어있는 현상
아마 reloadable 뒤에 앞쪽 comp가 다시 정의돼있어서 그런 것 같은데

세부 내용은 나중에 적어둘께요 일단 등록만

**Comment by csh1668** [comment]
![image](https://github.com/csh1668/RimworldExtractor/assets/18442452/1a24e1b9-e04d-4a82-9700-1034c27e9aeb)
제가 했을땐 잘 뜨던데 재현이 필요합니다.
시도해볼만한 조치: Prefabs.dat 삭제

**Comment by RimWorldKorea** [comment]
제가 설명을 이상하게 했네요..

그니깐
상식적(제일 조상 노드까지 거슬러 올라가서 0번을 매기는 방식)으로는 저 부분이 6번이 되야 하는게 맞을 테지만
실제로 게임 내에서 저 노드는 6번이 아닌 0번에 해당하는 노드였다는 뜻이예요

예를 들어서

    조상1 Def에 정의된 compA
    조상2 Def에 정의된 compB
    ...
    조상5 Def에 정의된 compE
    자식  Def에 정의된 compF

이기 때문에 compF는 6번이 될 것으로 여겼고, 추출도 그렇게 되었지만 실제로 compF는 0번 comp였고

    조상1 Def에 정의된 compA
    조상2 Def에 정의된 compB
    ...
    조상5 Def에 정의된 compE
    자식  Def에 정의된 compF
    자식  Def에 정의된 compA
    자식  Def에 정의된 compB
    ...
    자식  Def에 정의된 compE

실제 Def가 정의된 파일을 뒤져보니 위와 같은 식으로 돼있는데, 이것 때문이 아닐까? 해서요

**Comment by csh1668** [comment]
보니까
``` xml
<comps Inherit="False">
```
이거 때문에 그런거 같네요 저 부분은 상속에 반영하면 안되는거였음
