### ISSUE TITLE
xlsx -> xml 변환시 변환이 안되는 부분

### ISSUE THREAD

**Issue by zilrty** [csh1668/RimworldExtractor#19]
![1](https://github.com/csh1668/RimworldExtractor/assets/132768180/97168f5c-b2dc-4b5e-b7e8-f14e5c9b7eff)

처음 번역데이터 추출할때 저런식으로 부모노드를 못찾는애들은

![2](https://github.com/csh1668/RimworldExtractor/assets/132768180/9bfc5d7e-eb89-4920-b6e6-71d3de4f7dfe)

엑셀에 추출이 되긴하는데

막상 번역을 끝내고 xlsx -> xml 변환 하면

부모 노드 못찾는 저 부분만 xml로 변환이 안됨

모드 : https://steamcommunity.com/sharedfiles/filedetails/?id=3209604085

번역파일 : [Ilya Tech - Core (Continued) - 3209604085.zip](https://github.com/csh1668/RimworldExtractor/files/15466413/Ilya.Tech.-.Core.Continued.-.3209604085.zip)

**Comment by zilrty** [comment]
뭔 문제인진 모르겠지만

저 노드 없는 친구들은 엑셀 클래스 열이 Thingdef 였고

변환되서 번역이 된 친구들은 thingdef 여서

그냥 전부다 하나로 통일하니 변환도 잘되고 번역도 잘되네여

**Comment by csh1668** [comment]
보니까 모드 파일에서 thingdef(소문자)로 정의되어 있나보네요..? 이래도 적용되는건가 ㅋㅋ 요것도 조만간 고려하도록 하겠습니다 구현은 어렵지 않을거같음

**Comment by zilrty** [comment]
네 소문자로 해도 통일만 되면 다 적용 되더라구요
