### ISSUE TITLE
미리 정의된 FactionDef 속성

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#20]
[MustTranslate]
	public string pawnSingular = "member";

	[MustTranslate]
	public string pawnsPlural = "members";

	[MustTranslate]
	public string leaderTitle = "leader";

XML 파일에서 FactionDef를 발견할 시
위 세 가지 노드가 XML에서 정의돼있지 않을 경우
추출 파일에 해당 노드를 채워주는 기능이 필요해요

`FactionDef+exampleDef.pawnSingular` → `member`
`FactionDef+exampleDef.pawnsPlural` → `members`
`FactionDef+exampleDef.leaderTitle` → `leader`

**Comment by csh1668** [comment]
확인
최근에 제가 셤기간이라 좀 바쁩니당 주말에 시간 남으면 작업할게요
