### ISSUE TITLE
텍스트를 변경하는 Replace 패치 감지

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#21]
Replace 패치 중에 다른 노드의 텍스트를 바꾸는 용도로 사용한 것들이 있는데
이런 것도 추출시 포함할 필요가 있어보여요

[예시]
모드: https://steamcommunity.com/sharedfiles/filedetails/?id=2927323805

	<li Class="PatchOperationReplace">
		<xpath>/Defs/GeneDef[defName="AG_ArmourMinor"]/label</xpath>
		<value>
			<label>wooden skin</label>
		</value>
	</li>	
	<li Class="PatchOperationReplace">
		<xpath>/Defs/GeneDef[defName="AG_ArmourMinor"]/description</xpath>
		<value>
			<description>Hard, wood-like skin. This confers a small amount of natural armour.</description>
		</value>
	</li>	
	<li Class="PatchOperationReplace">
		<xpath>/Defs/HediffDef[defName="AG_ArmourMinor"]/label</xpath>
		<value>
			<label>wooden skin</label>
		</value>
	</li>	
	<li Class="PatchOperationReplace">
		<xpath>/Defs/HediffDef[defName="AG_ArmourMinor"]/description</xpath>
		<value>
			<description>Hard, wood-like skin. This confers a small amount of natural armour.</description>
		</value>
	</li>

**Comment by csh1668** [comment]
![image](https://github.com/csh1668/RimworldExtractor/assets/18442452/520f25aa-658b-4209-80b5-2e9e554c39cb)
Alpha Genes를 참조 모드로 추가하면 해결됩니당

참조 모드를 자동으로 선택하는 기능에 Patches를 넣지 않은 이유는 그거까지 고려하면 끝도 없어져서 그래요.
CE의 경우(최악의 경우) 참조 모드 하나 탐색하는 과정에서 몇시간까지 걸릴 수도 있어요
