### ISSUE TITLE
풀리스트의 xml->xlsx 변환에서의 동작 개선

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#22]
<img width="1306" alt="화면 캡처 2024-06-10 174831" src="https://github.com/csh1668/RimworldExtractor/assets/150018627/894ca9e7-16e7-40c8-a85e-5744387525ad">

참조: #13 
예시 파일: https://github.com/RimWorldKorea/RMK/issues/1014

이제 리스트 요소 수에 따라서 노드 개수는 맞게 나오는데
각 리스트의 값들이 뭉쳐지는건 여전해요

**Comment by csh1668** [comment]
수정완료

**Comment by RimWorldKorea** [comment]
헉 너무 빠름
