### ISSUE TITLE
수동 입력 옵션에서 개행 금지

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#23]
<img width="354" alt="화면 캡처 2024-06-10 180718" src="https://github.com/csh1668/RimworldExtractor/assets/150018627/ad4c6f7b-4fc8-41c0-a293-bf2fc7b40afd">

여기 줄바꿈이 들어가면 동작이 안되는 오류가 생기는데
막상 입력 창이 작아서 엔터가 들어갔는지 확인이 힘들더라구요

옛날에 한 번 그래서 삽질하다가 prefabs 파일 열어보고 알아챈 적이 있었어요

**Comment by csh1668** [comment]
금지는 안하지만 공백이나 개행문자는 저장되지 않게 변경했습니당
