### ISSUE TITLE
추출 불가능 노드

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#3]
[Tweaks Galore](https://steamcommunity.com/sharedfiles/filedetails/?id=2695164414) 모드에서
`\1.5\Defs\TweakDefs\Tweaks_Vanilla\Section_Mechanoids.xml`의
`TweaksGalore.TweakDef+Tweak_PreReleaseShipParts.description`이 추출이 안돼요

CDATA 처리가 돼있어서 그런가?

**Comment by csh1668** [comment]
그런듯요
암튼 반영 완료
