### ISSUE TITLE
분석기 의견

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#5]
**1.**
<img width="360" alt="화면 캡처 2024-04-17 003005" src="https://github.com/csh1668/RimworldExtractor/assets/150018627/f48ab533-707a-41a1-8d9c-63ac19ce11df"><br>

원본도 놔두고 싶을 때 미리 파일 탐색기를 왔다갔다 하지 않아도 되도록
`원본 파일 보존` 이라던지 `복사본을 만들어서 수정` 같은 옵션이 있으면 좋을 것 같아요

**2.**
<img width="280" alt="화면 캡처 2024-04-17 003259" src="https://github.com/csh1668/RimworldExtractor/assets/150018627/d7fe2559-b2e2-40b2-8c15-0f70a07effe6"><br>

대상 파일이 열려있는 상태일 때 분석을 시도하면 그대로 바보가 돼요
오류창 띄워주고 그냥 뱉도록 하는게 좋을 것 같아요

**3.**
<img width="90" alt="화면 캡처 2024-04-17 003651" src="https://github.com/csh1668/RimworldExtractor/assets/150018627/6fca661f-683b-4a10-88a0-a14f6bff70e9"><br>

덧붙이기 모드 뿐 아니라 [예전에 말했던 것](https://github.com/RimWorldKorea/RMK/discussions/496#discussioncomment-8957128) 처럼 재구성하기? 병합하기? 모드도 있어야 할 것 같아요

일반적으로 추출을 하게 되면 원본 xml 상에서 거리가 가까운 노드들은 비슷한 곳에 뭉쳐있으니까
번역할때 한 눈에 서로 참고하면서 작업을 할 수 있는데
시트 맨 밑에 따로 모아놓으면 그게 좀 힘들어지는 면이 있더라구요

**Comment by csh1668** [comment]
셤 끝나고 작업하는 걸로..
담주 토요일부터 작업하겠읍니다

**Comment by csh1668** [comment]
수정 완료
