### ISSUE TITLE
번역 분석기 오류

### ISSUE THREAD

**Issue by zilrty** [csh1668/RimworldExtractor#7]
WVC - Xenotypes and Genes - 2886992038
(https://steamcommunity.com/sharedfiles/filedetails/?id=2886992038)

분석할 엑셀파일 - [WVC - Xenotypes and Genes - 2886992038.xlsx](https://github.com/csh1668/RimworldExtractor/files/15051342/WVC.-.Xenotypes.and.Genes.-.2886992038.xlsx)

로그파일 - [log.txt](https://github.com/csh1668/RimworldExtractor/files/15051346/log.txt)

![1](https://github.com/csh1668/RimworldExtractor/assets/132768180/a8d873c8-b4ae-422b-858b-785039abecb6)

모드가 문제인지 추출기가 문제인진 모르겠지만 일단 제보해봄

**Comment by csh1668** [comment]
엑셀 파일에 있는 어떤 텍스트값이 문제인거 같은데 함 확인해봐야겠네요
이번주까지 시험이라서 주말에 작업하겠읍니다.. 😭

**Comment by zilrty** [comment]
급한거 아니니 천천히 하셔도 됨미다

시험 화이팅

**Comment by csh1668** [comment]
일단 에러가 안뜨게 하긴 했는데 엑셀 관련 외부 라이브러리 이슈라 제가 고칠게 없네요 😢
