### ISSUE TITLE
풀리스트 노드를 xml로 변환시 너무 긴 파일명

### ISSUE THREAD

**Issue by RimWorldKorea** [csh1668/RimworldExtractor#9]
`어쩌구저쩌구 모드 이름 - 스팀번호 어쩌구저쩌구 기다란 노드주소` 해서 파일명이 한없이 늘어지는데

이거 때문에 오류가 생겨서 추가로 수정해줘야 하더라구요

깃헙 데스크탑으로 하면 아예 커밋이 안되기도 하구요

그냥 `모드이름 - 스팀번호_구분용 숫자` 정도만 해도 충분하지 않을까 싶어요

**Comment by csh1668** [comment]
반영 완료
그걸 생각못했네요...
